<?php
/**
* Implementation of hook_webform_select_options_info().
* See webform/webform_hooks.php for further information on this hook in the Webform API.
*/
function webform_optionlists_webform_select_options_info() {
  $items = array();
  $items['one_onehundred'] = array(
    'title' => t('Numbers 1-100'),
    'options callback' => 'webform_optionlists_options_one_onehundred'
  );
  return $items;
}
/**
* Build an options list for use by webforms.
*/
function webform_optionlists_options_one_onehundred() {
  $options = array();
  for ($x=1; $x <= 100; $x++) {
    $options[$x] = $x;
  }
  return $options;
}
