<?php
/**
* Implementation of hook_webform_select_options_info().
* See webform/webform_hooks.php for further information on this hook in the Webform API.
*/
function webform_optionlists_webform_select_options_info() {
  $items = array();
  $items['one_onehundred'] = array(
    'title' => t('Numbers 1-100'),
    'options callback' => 'webform_optionlists_options_one_onehundred'
  );
  $items['agree'] = array(
  'title' => t('Agree/Disagree 4'),
  'options callback' => 'webform_optionlists_agree_disagree_4'
  );
  return $items;
}
/**
* Build an options list for use by webforms.
*/
function webform_optionlists_options_one_onehundred() {
  $options = array();
  for ($x=1; $x <= 100; $x++) {
    $options[$x] = $x;
  }
  return $options;
}

function webform_optionlists_agree_disagree_4() { 
 $options = array (
  'SA' => t('Strongly Agree'),
  'A'  => t('Agree'),
  'D'  => t('Disagree'),
  'SD' => t('Strongly Disagree'), 
  'NA' => t('Not Applicable'),
  );
  return $options;

}
